### ISSUE TITLE
Add support for Schema tags

### ISSUE THREAD

**Issue by markbates** [gobuffalo/tags#1]
http://www.gorillatoolkit.org/pkg/schema

**Comment by apaganobeleno** [comment]
@markbates on this one, what would you like to achieve with the Schema integration? i've been thinking about adding the field name based on the `schema` field tag, but other than that i wonder if we should support things like nested structs and so on.

Looking forward to work on this one :)

**Comment by markbates** [comment]
That was basically it for this one. Setting the name of input tag to the name set using schema. If there isn't a schema tag, just use the attribute name, which is what we do now.

**Comment by apaganobeleno** [comment]
closed by #16
