### ISSUE TITLE
How to use inputtags with materialize theme

### ISSUE THREAD

**Issue by vikram-rawat** [gobuffalo/tags#110]
Somehow the form_for input tag come with a div wrapper of class form-group and a label.

But in materialize you have to shove elements inside a div in hierarchical order.

I am working with materialize theme and I am trying to take advantage of form_for function.

Please guide me how should I do it.

**Comment by stanislas-m** [comment]
We do not support materialize, but you can create your own package : copy https://github.com/gobuffalo/tags/tree/master/form/bootstrap, and adapt it to your needs.
