### ISSUE TITLE
Are there any specific tags for name argument

### ISSUE THREAD

**Issue by vikram-rawat** [gobuffalo/tags#111]
If I design my own form. Can I use some tags in name arguments so to connect it with form_for methods.

Like I create my own form and wrap it in form_for and use specific arguments in name. By which I can design the entire form exactly the way I want but with security and ease of form_for function.

This way we can use any CSS framework we want and still connect it with form_for.

If it's already available. Please tell me how can I use it. Please do reply.

**Comment by mclark4386** [comment]
Are you not able meet your needs with the ‘class’ option?

**Comment by vikram-rawat** [comment]
I want to use materialize and bootstrap input are wrapped inside a div element of class form-group which is troublesome to change in raw form to materialize.

I just want to know if there is any method where I can call a function in name argument and get all the benefits of form_for method in my custom designed form.

**Comment by mclark4386** [comment]
The base form and form_for tags shouldn't have the bootstrap classes....maybe I'm miss understanding something... would you mind giving an example of what you are getting and what you want to get?
