### ISSUE TITLE
[Suggestion] Add Selected() to Selectable for multiple.

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/tags#117]
Why not extend the Selectable intefrace like this:
```
type Selectable interface {
	SelectValue() interface{}
	SelectLabel() string
        Selected() bool
}
```
so if I have a select multiple i can manage selected items?

**Comment by markbates** [comment]
Adding to the interface would be a breaking change. However, your idea is good, and can be accomplished by adding a new, optional, interface:

```go
type T interface {
  IsSelected() bool
}
```

and then checking to see if the `Selectable` interface passed in, also supports `T`.

PR's are welcome. :)

**Comment by badstorm** [comment]
Thanks for your suggestion. I do this and works great:

in tags/form i created **_selectable_multiple.go_**:
```
package form

//SelectableMultiple allows any struct to add Selected option in the select tag.
type SelectableMultiple interface {
	IsSelected() bool
}

//SelectableMultiples is the plural for SelectableMultiple
type SelectableMultiples []SelectableMultiple
```
Then i replace this (from line 138 to 141) in _tags/form/select_tag.go_:
```
if rv.Index(i).Type().Implements(selectableType) {
				so = append(so, SelectOption{Value: x.(Selectable).SelectValue(), Label: x.(Selectable).SelectLabel()})
				continue
			}

```
with this:
```
if rv.Index(i).Type().Implements(selectableType) {
				isSelected := false
				selectableMultipleType := reflect.TypeOf((*SelectableMultiple)(nil)).Elem()
				if rv.Index(i).Type().Implements(selectableMultipleType) {
					isSelected = x.(SelectableMultiple).IsSelected()
				}
				so = append(so, SelectOption{Value: x.(Selectable).SelectValue(), Label: x.(Selectable).SelectLabel(), Selected: isSelected})
				continue
			}
```

Now in any struct simply add:
```
func (m MyModel) IsSelected() bool {
	...
}
```
If this solution  is ok, I can make a PR! ;)

**Comment by markbates** [comment]
If you have a solution, then please open a PR. It's easier to discussion your changes with the context that a PR provides.
