### ISSUE TITLE
Form options for HTML5 properties like placeholder

### ISSUE THREAD

**Issue by nzoschke** [gobuffalo/tags#23]
It would be nice to specify a html5 placeholder attribute for form fields.

`<%= f.InputTag("Email", {placeholder: "me@example.com"}) %>`

**Comment by nzoschke** [comment]
BTW, loving the buffalo framework. I can scratch my own itch with a PR here if it makes sense for the tags package.

**Comment by apaganobeleno** [comment]
Hey @nzoschke thanks for reporting, could you give a bit more context ? i've tried this one by doing:

<%= f.InputTag("Name",{"placeholder": "something"}) %> 

and it correctly generates:

<div class="form-group">
    <label>Name</label>
   <input class=" form-control" id="user-Name" name="Name" placeholder="something" type="text" value="">
</div>

May i be missing something ?

**Comment by nzoschke** [comment]
That indeed works. Thanks for the pointer, closing this issue.
