### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by markbates** [gobuffalo/tags#3]

**Comment by apaganobeleno** [comment]
@markbates would you like to move the README to Plush or should we provide example for both ?

**Comment by markbates** [comment]
Yeah, it should be updated for plush.

**Comment by apaganobeleno** [comment]
I can take care of this one if you agree

**Comment by apaganobeleno** [comment]
Appart from that, what else should we do to cover this one ?

**Comment by markbates** [comment]
Yes please!

**Comment by apaganobeleno** [comment]
#9 moves the template examples to plush, @markbates is there anything else we should do to improve the README ?
