### ISSUE TITLE
Add support for error handling

### ISSUE THREAD

**Issue by markbates** [gobuffalo/tags#4]
https://github.com/markbates/validate

**Comment by apaganobeleno** [comment]
@markbates i've been thinking in this one with the following approach, i wanted to discuss it before starting to code it:

```erb
 <%= form_for(newUser, {action: "/users", class: "new-form", errors: userErrors }) { %>
            <div class="col-md-3">
                <%= f.InputTag("FirstName", {placeholder:"First Name", label: "First Name"}) %>
            </div>
```

that generates something like:

```html
<div></div>
<form action="/users" class="new-form" id="user-form" method="POST">
    <div class="col-md-3">
       <div class="form-group **has-error**">
            <label>First Name</label>
            <input class=" form-control" id="user-FirstName" name="FirstName" placeholder="First Name" type="text" value="">
            <span class="help-block">First Name cannot be empty.</span>
       </div>
    </div>
...
</form>
```

For the fields that have errors.
`userErrors` should have been `Set` on the action after proper validation and it should be the output of a model validation (*Errors).

Thoughts ?

**Comment by markbates** [comment]
Yes! That's exactly what I was hoping for.

**Comment by apaganobeleno** [comment]
ok, awesome, i can work on this one over the week, i'll keep you posted, thanks for the quick answer Mark

**Comment by markbates** [comment]
woot! awesome. i can't wait!

**Comment by apaganobeleno** [comment]
Its always a pleasure @markbates, trying to organize my time better to have some more time to enjoy adding things into tags and buffalo, thanks for the chance and the guidance.
