### ISSUE TITLE
Move the docs to the Wiki section

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/tags#45]
The current Readme is quite verbose, and not easy to maintain. We should use the Wiki and split the contents into several pages.

**Comment by paganotoni** [comment]
This is a great idea, I was thinking that we should move this to be inside a tags section on  gobuffalo.io but that may be too much, moving it to the Wiki would be a good start.

**Comment by stanislas-m** [comment]
@paganotoni In my opinion, it's a good thing to have a separate documentation for components like `tags`. They can be used outside the Buffalo context, and it prevents the Buffalo.io doc site to become a bloatware.

**Comment by paganotoni** [comment]
@stanislas-m I just added pagination docs on the Wiki, would love to get your feedback on it.

**Comment by stanislas-m** [comment]
@paganotoni Just one thing: it would be cool to add an example using some of the options, just after the options list.

Overall it's nice. :)

**Comment by paganotoni** [comment]
All set on that, thanks for the review!

**Comment by paganotoni** [comment]
@stanislas-m I'm closing this issue given we've already moved docs to the Wiki, on an upcoming release 1.9.5 we'll remove docs from README.md and have all docs only in the Wiki.
