### ISSUE TITLE
Clarify the difference between form_for and form

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/tags#50]
The docs mix the tags from `form_for` and `form`, we need to clarify it.

**Comment by paganotoni** [comment]
@stanislas-m I updated the documentation, I think this one is covered but will need your help reviewing the docs if you find something we need to change please LMK, thanks in advance for adding this one.

Closing this one and looking forward for your feedback!

**Comment by stanislas-m** [comment]
That's great, thanks!
