### ISSUE TITLE
Should Tags provide template helpers ?

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/tags#72]
@markbates I'm thinking that template helpers that deal with tags (form_for, form, bootstrap versions and others) should be part of Tags and plush would just use those helpers as [it is using them now](https://github.com/gobuffalo/plush/blob/master/helpers.go#L42).

Do you agree with this?

**Comment by markbates** [comment]
No, I don’t. :)

If you put them in tags then it now has a plush dependency. 

If we keep it in plush then it has a tags dependency, which I think is better. 

Tags can be used without plush, but the reverse isn’t necessarily true.

**Comment by paganotoni** [comment]
I was thinking that we could have equal interfaces between Tags and Plush so we don't have any dependency on Plush, but I think I can see your point and don't have any solid argument to put us into all this work, so I'll close this one.
