### ISSUE TITLE
Option to generate raw tags when using bootstrap form

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/tags#73]
When using bootstrap `form_for` and `form` helper tags are generated with some div wrappers around them, it would be good to provide an option to render the raw input without any wrappers around.

**Comment by markbates** [comment]
Isn’t that what the non bootstrap helpers do?

**Comment by paganotoni** [comment]
Yes, but this is for someone who wants just one or two tags to be raw and the rest to be bootstrap, this usually happens with checkboxes and radio buttons but could be also helpful when adding customized inputs (like a double slider that's built with JS) to your form.

**Comment by markbates** [comment]
Got it. Sounds like a good idea. something like `tag_only: true` or something like that?

**Comment by paganotoni** [comment]
Yes, @markbates something like that

**Comment by paganotoni** [comment]
Covered by #76
