### ISSUE TITLE
Bad Label Render

### ISSUE THREAD

**Issue by alphonse927** [gobuffalo/tags#78]
When I try to add a Tag, with Form or Form_for with the prop all Uppercased, for example:
`<%= f.InputTag("URL") %>`
The label generated for that tag is spaced like: 
`U R L`

**Comment by paganotoni** [comment]
hey @alphonse927 thanks for reporting, lets ads this fix in 1.9.6

**Comment by markbates** [comment]
In the mean time you can set a custom label using the options.
