### ISSUE TITLE
Doc: update Select Tag example with "ordered array" example

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/tags#94]
The version 2 of tags has "in order" selects welcome feature.
We need to update the documentation with the following example INSTEAD of the previous.
I think most users will want to have in order list , and having an example out of order will just confuse most users.
So we could add:
1) a time series like this : 
``
<%= f.SelectTag("Language", { options: [{"None": 1},{"Arabic": 6145},{"Chinese": 2052},{"English": 2057}, {"French": 1036},{"German": 1031}, {"Hindi": 1081}, {"Japanese": 1041},  {"Portuguese": 2070},  {"Russian": 1049}, {"Spanish": 1034}]}) %>
``
``
2) A country list like this :  
<%= f.SelectTag("Country", { options: [{"Select your country": "None"},{"Brazil": "Brazil"},{"China": "China"},{"Denmark": "Denmark"},{"Finland": "Finland"},{"France": "France"},{"Germany": "Germany"},{"Ireland": "Ireland"},{"Israel": "Israel"},{"Italy": "Italy"},{"Japan": "Japan"},{"Luxembourg": "Luxembourg"},{"Mexico": "Mexico"},{"Morocco": "Morocco"},{"Netherlands": "Netherlands"},{"Norway": "Norway"},{"Poland": "Poland"},{"Portugal": "Portugal"},{"Russia": "Russia"},{"South Africa": "South Africa"},{"South Korea": "South Korea"},{"Spain": "Spain"},{"Sweden": "Sweden"},{"Switzerland": "Switzerland"},{"Taiwan": "Taiwan"},{"Thailand": "Thailand"},{"Tunisia": "Tunisia"},{"United Kingdom (UK)": "United Kingdom"},{"United States of America (USA)": "USA"}]}) %>
``

https://github.com/gobuffalo/tags/wiki/Select-Tag

**Comment by paganotoni** [comment]
Added it, thanks @hubyhuby!
